package calculadora;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author User
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldValor2 = new javax.swing.JTextField();
        jTextFieldValor1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3Resultado = new javax.swing.JTextField();
        jButton1Soma = new javax.swing.JButton();
        jButton2Subtracao = new javax.swing.JButton();
        jButton3Multiplicacao = new javax.swing.JButton();
        jButton4Divisao = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Calculadora");

        jLabel2.setText("Valor 1:");

        jLabel3.setText("Valor 2:");

        jTextFieldValor2.addActionListener(this::jTextFieldValor2ActionPerformed);

        jLabel4.setText("Resultado:");

        jButton1Soma.setText("SOMA");
        jButton1Soma.addActionListener(this::jButton1SomaActionPerformed);

        jButton2Subtracao.setText("SUBTRAÇÃO");
        jButton2Subtracao.addActionListener(this::jButton2SubtracaoActionPerformed);

        jButton3Multiplicacao.setText("MULTIPLICAÇÃO");
        jButton3Multiplicacao.addActionListener(this::jButton3MultiplicacaoActionPerformed);

        jButton4Divisao.setText("DIVISÃO");
        jButton4Divisao.addActionListener(this::jButton4DivisaoActionPerformed);

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(this::jButtonAlterarActionPerformed);

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(this::jButtonLimparActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jTextField3Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1Soma)
                                .addGap(58, 58, 58)
                                .addComponent(jButton2Subtracao)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonAlterar)
                                .addGap(71, 71, 71)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3Multiplicacao)
                                .addGap(40, 40, 40)
                                .addComponent(jButton4Divisao))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButtonLimpar)))))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(140, 140, 140)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1Soma)
                    .addComponent(jButton2Subtracao)
                    .addComponent(jButton3Multiplicacao)
                    .addComponent(jButton4Divisao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonLimpar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldValor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValor2ActionPerformed
    // Evento executado quando o botão SUBTRAÇÃO é clicado
    private void jButton2SubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2SubtracaoActionPerformed
        // TODO add your handling code here:

        // Declara três variáveis inteiras:
        // num1 = primeiro número
        // num2 = segundo número
        // res = resultado
        int num1, num2, res;
        // Pega o texto digitado no campo Valor 1
        // e transforma esse texto em um número inteiro
        num1 = Integer.parseInt(jTextFieldValor1.getText());
        // Pega o texto digitado no campo Valor 2
        // e transforma esse texto em um número inteiro 
        num2 = Integer.parseInt(jTextFieldValor2.getText());

        res = num1 - num2;

        // Converte o resultado para texto
        // e coloca esse texto no campo Resultado
        jTextField3Resultado.setText(String.valueOf(res));
    }//GEN-LAST:event_jButton2SubtracaoActionPerformed

    private void jButton3MultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3MultiplicacaoActionPerformed
        // TODO add your handling code here:
        int num1, num2, res;
        num1 = Integer.parseInt(jTextFieldValor1.getText());
        num2 = Integer.parseInt(jTextFieldValor2.getText());

        res = num1 * num2;
        jTextField3Resultado.setText(String.valueOf(res));
    }//GEN-LAST:event_jButton3MultiplicacaoActionPerformed
    // Evento executado quando o botão SOMA é clicado
    private void jButton1SomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SomaActionPerformed
        // TODO add your handling code here:
        int num1, num2, res;
        num1 = Integer.parseInt(jTextFieldValor1.getText());
        num2 = Integer.parseInt(jTextFieldValor2.getText());

        res = num1 + num2;
        jTextField3Resultado.setText(String.valueOf(res));
    }//GEN-LAST:event_jButton1SomaActionPerformed
    // Evento executado quando o botão DIVIDIR é clicado
    private void jButton4DivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4DivisaoActionPerformed
        // Variáveis para guardar os números
        int num1, num2;
        // Variável resultado é float porque a divisão
        // pode gerar casas decimais
        float res;
        // Pega o primeiro valor digitado e transforma em inteiro
        num1 = Integer.parseInt(jTextFieldValor1.getText());
        num2 = Integer.parseInt(jTextFieldValor2.getText());
        // Faz a divisão
        // (float) permite que o resultado tenha casas decimais
        res = (float) num1 / num2;
        // Mostra o resultado na tela
        jTextField3Resultado.setText(String.valueOf(res));
    }//GEN-LAST:event_jButton4DivisaoActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        jLabel1.setText("Minha Calculadora");

    }//GEN-LAST:event_jButtonAlterarActionPerformed
    // Evento executado quando o botão LIMPAR é clicado
    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // Limpa os campos onde foi digitado os valores
        jTextFieldValor1.setText("");
        jTextFieldValor2.setText("");
        jTextField3Resultado.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Soma;
    private javax.swing.JButton jButton2Subtracao;
    private javax.swing.JButton jButton3Multiplicacao;
    private javax.swing.JButton jButton4Divisao;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3Resultado;
    private javax.swing.JTextField jTextFieldValor1;
    private javax.swing.JTextField jTextFieldValor2;
    // End of variables declaration//GEN-END:variables
}
