/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadoraimc;

/**
 *
 * @author 1104695
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1Calcular = new javax.swing.JButton();
        jButton2Limpar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1Altura = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3Peso = new javax.swing.JLabel();
        jLabel4Resultado = new javax.swing.JLabel();
        jTextField2Peso = new javax.swing.JTextField();
        jTextField2Resultado = new javax.swing.JTextField();
        jTextField2Altura = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1Calcular.setText("Calcular IMC");

        jButton2Limpar.setText("Limpar");

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1Altura.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1Altura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1Altura.setText("ALTURA");

        jLabel3Peso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3Peso.setText("PESO");

        jLabel4Resultado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4Resultado.setText("RESULTADO");

        jTextField2Peso.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2Peso.setForeground(new java.awt.Color(51, 51, 51));
        jTextField2Peso.addActionListener(this::jTextField2PesoActionPerformed);

        jTextField2Resultado.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2Resultado.setForeground(new java.awt.Color(51, 51, 51));
        jTextField2Resultado.addActionListener(this::jTextField2ResultadoActionPerformed);

        jTextField2Altura.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2Altura.setForeground(new java.awt.Color(51, 51, 51));
        jTextField2Altura.addActionListener(this::jTextField2AlturaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1Calcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2Limpar)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField2Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1Altura)
                                            .addComponent(jLabel2))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4Resultado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                        .addComponent(jTextField2Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jTextField1))
                        .addGap(52, 52, 52))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(233, Short.MAX_VALUE)
                    .addComponent(jTextField2Altura, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(52, 52, 52)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3Peso)
                    .addComponent(jTextField2Peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1Altura)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4Resultado)
                    .addComponent(jTextField2Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1Calcular)
                    .addComponent(jButton2Limpar))
                .addGap(29, 29, 29))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(jTextField2Altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(188, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2PesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2PesoActionPerformed

    }//GEN-LAST:event_jTextField2PesoActionPerformed

    private void jTextField2ResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ResultadoActionPerformed
     double num1 = Double.parseDouble(jTextField2Peso.getText());
     double num2 = Double.parseDouble(jTextField2Altura.getText());
     double resposta = num1/(num2*num2);
     resultado.setText(String.valueOf(resposta));
    }//GEN-LAST:event_jTextField2ResultadoActionPerformed

    private void jTextField2AlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2AlturaActionPerformed

    }//GEN-LAST:event_jTextField2AlturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Calcular;
    private javax.swing.JButton jButton2Limpar;
    private javax.swing.JLabel jLabel1Altura;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3Peso;
    private javax.swing.JLabel jLabel4Resultado;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2Altura;
    private javax.swing.JTextField jTextField2Peso;
    private javax.swing.JTextField jTextField2Resultado;
    // End of variables declaration//GEN-END:variables
}
