/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadoraimc;

/**
 *
 * @author 1104695
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonCalcular = new javax.swing.JButton();
        jButton2Limpar = new javax.swing.JButton();
        jLabel1Altura = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3Peso = new javax.swing.JLabel();
        jLabel4Resultado = new javax.swing.JLabel();
        jTextField2Peso = new javax.swing.JTextField();
        jTextField2Altura = new javax.swing.JTextField();
        jTextFieldResultado = new javax.swing.JTextField();
        jTextField1Classificacao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCalcular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonCalcular.setText("Calcular IMC");
        jButtonCalcular.addActionListener(this::jButtonCalcularActionPerformed);

        jButton2Limpar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2Limpar.setText("Limpar");
        jButton2Limpar.addActionListener(this::jButton2LimparActionPerformed);

        jLabel1Altura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1Altura.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1Altura.setText("ALTURA(m)");

        jLabel3Peso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3Peso.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3Peso.setText("PESO (kg)");

        jLabel4Resultado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4Resultado.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4Resultado.setText("Seu IMC:");

        jTextField2Peso.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2Peso.setForeground(new java.awt.Color(51, 51, 51));
        jTextField2Peso.addActionListener(this::jTextField2PesoActionPerformed);

        jTextField2Altura.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2Altura.setForeground(new java.awt.Color(51, 51, 51));
        jTextField2Altura.addActionListener(this::jTextField2AlturaActionPerformed);

        jTextFieldResultado.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldResultado.setForeground(new java.awt.Color(51, 51, 51));

        jTextField1Classificacao.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1Classificacao.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Classificação");

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Calculadora IMC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jButton2Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4Resultado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel2))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)
                                    .addComponent(jTextField1Classificacao)))
                            .addComponent(jTextField2Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1Altura, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3Peso)
                            .addComponent(jTextField2Altura, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3Peso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2Peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1Altura)
                .addGap(7, 7, 7)
                .addComponent(jTextField2Altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCalcular)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4Resultado)
                    .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1Classificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jButton2Limpar)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2PesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2PesoActionPerformed

    }//GEN-LAST:event_jTextField2PesoActionPerformed

    private void jTextField2AlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2AlturaActionPerformed

    }//GEN-LAST:event_jTextField2AlturaActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        double num1 = Double.parseDouble(jTextField2Peso.getText());
        double num2 = Double.parseDouble(jTextField2Altura.getText());

        double resposta = num1 / (num2 * num2);
        jTextFieldResultado.setText(String.format("%2f", resposta));
        if (resposta < 18.5) {
            jTextField1Classificacao.setText("Abaixo do peso");
        } else if (resposta < 25) {
            jTextField1Classificacao.setText("Peso normal");
        } else if (resposta < 30) {
            jTextField1Classificacao.setText("Sobrepeso");
        } else {
            jTextField1Classificacao.setText("Obesidade");
        }

    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jButton2LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2LimparActionPerformed
        jTextField2Altura.setText("");
        jTextField2Peso.setText("");
        jTextFieldResultado.setText("");
        jTextField1Classificacao.setText("");

    }//GEN-LAST:event_jButton2LimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2Limpar;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1Altura;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3Peso;
    private javax.swing.JLabel jLabel4Resultado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1Classificacao;
    private javax.swing.JTextField jTextField2Altura;
    private javax.swing.JTextField jTextField2Peso;
    private javax.swing.JTextField jTextFieldResultado;
    // End of variables declaration//GEN-END:variables
}
